In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#import tensorflow as tf
#import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score, precision_score, f1_score, accuracy_score
from sklearn.model_selection import KFold
from tabulate import tabulate

### Import Data

In [2]:
df_Average = pd.read_excel(r'C:\Users\linhc\OneDrive\Documents\Sproj\DataCollection\Importantfiles\TrainingValData\AverageTrainingVal.xlsx')
df_Skilled = pd.read_excel(r'C:\Users\linhc\OneDrive\Documents\Sproj\DataCollection\Importantfiles\TrainingValData\SkilledTrainingVal.xlsx')
df_Elite = pd.read_excel(r'C:\Users\linhc\OneDrive\Documents\Sproj\DataCollection\Importantfiles\TrainingValData\EliteTrainingVal.xlsx')

In [3]:
df_Elite

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,blueHeraldsBarons,blueTowersDestroyed,...,redEliteMonsters,redDragons,redHeraldsBarons,redTowersDestroyed,redTotalGold,redTotalDamageToChampions,redAvgLevel,redTotalMinionsKilled,redTotalJungleMinionsKilled,redGoldDiff
0,0,32,5,10,15,15,0,0,0,1,...,2,2,0,1,26016,22836,8.4,279,69,1063
1,1,49,6,10,14,6,1,1,0,0,...,0,0,0,1,25835,20998,8.6,301,77,3740
2,1,26,2,17,10,24,2,1,1,0,...,0,0,0,1,23499,25089,8.6,268,80,-5804
3,1,106,8,10,8,18,2,1,1,0,...,1,1,0,0,21625,21831,8.4,297,76,-2583
4,1,31,10,22,7,24,3,2,1,2,...,0,0,0,0,21954,19995,8.4,293,79,-9229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631,1,24,7,6,7,8,1,1,0,0,...,2,1,1,0,23558,19954,8.6,340,100,722
8632,1,20,8,15,9,13,1,1,0,1,...,1,0,1,1,24741,23249,8.8,317,79,-1783
8633,1,26,4,17,16,21,3,2,1,1,...,0,0,0,0,25491,31258,8.6,246,62,-2358
8634,1,27,9,7,13,11,1,1,0,0,...,1,0,1,1,25270,21193,9.0,297,68,2430
8635,0,20,4,8,13,4,1,0,1,0,...,1,1,0,1,28009,24678,9.6,387,87,4429

## Adding and subtract variable

In [4]:
def addVar(df): 
    df['blue/redAvgLevel'] = round(df['blueAvgLevel']/df['redAvgLevel'],5)
    df['blue/redTotalDamageToChampions'] = round(df['blueTotalDamageToChampions']/df['redTotalDamageToChampions'],5)
    df['red/blueKills'] = round(df['blueKills']/df['redKills'],5)
    df['blueAvgLevel/redAvgLevel'] = round(df['blueAvgLevel']/df['redAvgLevel'],5)
    df = df.drop('redGoldDiff', axis=1)
    return df

In [5]:
df_Elite = addVar(df_Elite)
df_Average = addVar(df_Average)
df_Skilled = addVar(df_Skilled)
df_Elite

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,blueHeraldsBarons,blueTowersDestroyed,...,redTowersDestroyed,redTotalGold,redTotalDamageToChampions,redAvgLevel,redTotalMinionsKilled,redTotalJungleMinionsKilled,blue/redAvgLevel,blue/redTotalDamageToChampions,red/blueKills,blueAvgLevel/redAvgLevel
0,0,32,5,10,15,15,0,0,0,1,...,1,26016,22836,8.4,279,69,1.00000,1.09940,0.66667,1.00000
1,1,49,6,10,14,6,1,1,0,0,...,1,25835,20998,8.6,301,77,0.97674,0.92795,0.71429,0.97674
2,1,26,2,17,10,24,2,1,1,0,...,1,23499,25089,8.6,268,80,1.06977,1.20710,1.70000,1.06977
3,1,106,8,10,8,18,2,1,1,0,...,0,21625,21831,8.4,297,76,1.02381,1.09880,1.25000,1.02381
4,1,31,10,22,7,24,3,2,1,2,...,0,21954,19995,8.4,293,79,1.11905,1.73458,3.14286,1.11905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631,1,24,7,6,7,8,1,1,0,0,...,0,23558,19954,8.6,340,100,1.00000,0.80946,0.85714,1.00000
8632,1,20,8,15,9,13,1,1,0,1,...,1,24741,23249,8.8,317,79,1.00000,0.96520,1.66667,1.00000
8633,1,26,4,17,16,21,3,2,1,1,...,0,25491,31258,8.6,246,62,1.00000,1.12246,1.06250,1.00000
8634,1,27,9,7,13,11,1,1,0,0,...,1,25270,21193,9.0,297,68,0.97778,1.01321,0.53846,0.97778
8635,0,20,4,8,13,4,1,0,1,0,...,1,28009,24678,9.6,387,87,0.91667,0.65694,0.61538,0.91667

## Clean Data for Nan, Infinite and too large value

In [6]:
def clean_dataset(df):
    assert isinstance(df, pd.DataFrame), "df needs to be a pd.DataFrame"
    df.dropna(inplace=True)
    indices_to_keep = ~df.isin([np.nan, np.inf, -np.inf]).any(1)
    return df[indices_to_keep].astype(np.float64)

In [7]:
df_Elite.shape

(8636, 34)

In [8]:
df_Elite = clean_dataset(df_Elite)
df_Elite

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,blueHeraldsBarons,blueTowersDestroyed,...,redTowersDestroyed,redTotalGold,redTotalDamageToChampions,redAvgLevel,redTotalMinionsKilled,redTotalJungleMinionsKilled,blue/redAvgLevel,blue/redTotalDamageToChampions,red/blueKills,blueAvgLevel/redAvgLevel
0,0.0,32.0,5.0,10.0,15.0,15.0,0.0,0.0,0.0,1.0,...,1.0,26016.0,22836.0,8.4,279.0,69.0,1.00000,1.09940,0.66667,1.00000
1,1.0,49.0,6.0,10.0,14.0,6.0,1.0,1.0,0.0,0.0,...,1.0,25835.0,20998.0,8.6,301.0,77.0,0.97674,0.92795,0.71429,0.97674
2,1.0,26.0,2.0,17.0,10.0,24.0,2.0,1.0,1.0,0.0,...,1.0,23499.0,25089.0,8.6,268.0,80.0,1.06977,1.20710,1.70000,1.06977
3,1.0,106.0,8.0,10.0,8.0,18.0,2.0,1.0,1.0,0.0,...,0.0,21625.0,21831.0,8.4,297.0,76.0,1.02381,1.09880,1.25000,1.02381
4,1.0,31.0,10.0,22.0,7.0,24.0,3.0,2.0,1.0,2.0,...,0.0,21954.0,19995.0,8.4,293.0,79.0,1.11905,1.73458,3.14286,1.11905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8631,1.0,24.0,7.0,6.0,7.0,8.0,1.0,1.0,0.0,0.0,...,0.0,23558.0,19954.0,8.6,340.0,100.0,1.00000,0.80946,0.85714,1.00000
8632,1.0,20.0,8.0,15.0,9.0,13.0,1.0,1.0,0.0,1.0,...,1.0,24741.0,23249.0,8.8,317.0,79.0,1.00000,0.96520,1.66667,1.00000
8633,1.0,26.0,4.0,17.0,16.0,21.0,3.0,2.0,1.0,1.0,...,0.0,25491.0,31258.0,8.6,246.0,62.0,1.00000,1.12246,1.06250,1.00000
8634,1.0,27.0,9.0,7.0,13.0,11.0,1.0,1.0,0.0,0.0,...,1.0,25270.0,21193.0,9.0,297.0,68.0,0.97778,1.01321,0.53846,0.97778
8635,0.0,20.0,4.0,8.0,13.0,4.0,1.0,0.0,1.0,0.0,...,1.0,28009.0,24678.0,9.6,387.0,87.0,0.91667,0.65694,0.61538,0.91667

In [9]:
df_Skilled.shape

(22698, 34)

In [10]:
df_Skilled = clean_dataset(df_Skilled)
df_Skilled

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,blueHeraldsBarons,blueTowersDestroyed,...,redTowersDestroyed,redTotalGold,redTotalDamageToChampions,redAvgLevel,redTotalMinionsKilled,redTotalJungleMinionsKilled,blue/redAvgLevel,blue/redTotalDamageToChampions,red/blueKills,blueAvgLevel/redAvgLevel
0,1.0,22.0,4.0,8.0,11.0,7.0,1.0,0.0,1.0,0.0,...,0.0,23226.0,24196.0,8.6,285.0,71.0,1.00000,0.99248,0.72727,1.00000
1,1.0,21.0,9.0,13.0,9.0,14.0,2.0,2.0,0.0,0.0,...,0.0,23786.0,24326.0,8.8,294.0,87.0,1.02273,0.98010,1.44444,1.02273
2,0.0,35.0,1.0,8.0,9.0,8.0,0.0,0.0,0.0,0.0,...,0.0,22628.0,17172.0,9.0,288.0,53.0,0.95556,1.30323,0.88889,0.95556
3,0.0,73.0,4.0,9.0,2.0,6.0,2.0,1.0,1.0,0.0,...,1.0,21030.0,15260.0,8.4,332.0,79.0,1.04762,1.48938,4.50000,1.04762
4,0.0,25.0,2.0,6.0,14.0,5.0,0.0,0.0,0.0,0.0,...,2.0,28309.0,26304.0,9.0,330.0,92.0,0.93333,0.81201,0.42857,0.93333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22693,1.0,26.0,5.0,10.0,16.0,11.0,0.0,0.0,0.0,0.0,...,0.0,26463.0,31985.0,9.0,317.0,93.0,0.93333,0.87557,0.62500,0.93333
22694,1.0,28.0,8.0,7.0,12.0,7.0,2.0,1.0,1.0,0.0,...,1.0,26211.0,21955.0,9.0,336.0,84.0,0.95556,1.15864,0.58333,0.95556
22695,0.0,20.0,4.0,5.0,9.0,5.0,1.0,0.0,1.0,0.0,...,0.0,22489.0,25359.0,8.8,310.0,80.0,0.97727,0.89609,0.55556,0.97727
22696,0.0,19.0,5.0,7.0,13.0,6.0,0.0,0.0,0.0,0.0,...,1.0,25044.0,24404.0,8.8,253.0,90.0,1.00000,0.86969,0.53846,1.00000
22697,0.0,92.0,4.0,11.0,11.0,8.0,2.0,1.0,1.0,0.0,...,0.0,23436.0,29401.0,8.6,305.0,51.0,1.02326,0.94544,1.00000,1.02326

In [11]:
df_Average.shape

(56158, 34)

In [12]:
df_Average = clean_dataset(df_Average)
df_Average

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,blueHeraldsBarons,blueTowersDestroyed,...,redTowersDestroyed,redTotalGold,redTotalDamageToChampions,redAvgLevel,redTotalMinionsKilled,redTotalJungleMinionsKilled,blue/redAvgLevel,blue/redTotalDamageToChampions,red/blueKills,blueAvgLevel/redAvgLevel
0,0.0,45.0,2.0,7.0,9.0,5.0,1.0,1.0,0.0,0.0,...,0.0,22419.0,19383.0,8.4,265.0,76.0,0.97619,1.03962,0.77778,0.97619
1,1.0,23.0,2.0,21.0,4.0,18.0,3.0,2.0,1.0,1.0,...,1.0,17785.0,15894.0,8.2,230.0,44.0,1.09756,1.71216,5.25000,1.09756
2,1.0,24.0,4.0,15.0,11.0,21.0,1.0,1.0,0.0,0.0,...,0.0,24708.0,22326.0,8.8,310.0,60.0,0.97727,1.12842,1.36364,0.97727
3,0.0,21.0,4.0,14.0,20.0,10.0,1.0,0.0,1.0,0.0,...,0.0,28146.0,30193.0,9.2,284.0,84.0,0.91304,1.00437,0.70000,0.91304
4,0.0,18.0,2.0,10.0,14.0,3.0,0.0,0.0,0.0,1.0,...,0.0,23430.0,27102.0,8.4,215.0,64.0,1.00000,0.93318,0.71429,1.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56153,1.0,133.0,4.0,11.0,8.0,9.0,2.0,1.0,1.0,0.0,...,2.0,19440.0,14082.0,8.4,194.0,76.0,1.07143,1.45114,1.37500,1.07143
56154,0.0,17.0,5.0,11.0,8.0,13.0,1.0,1.0,0.0,0.0,...,1.0,24574.0,22157.0,8.4,295.0,92.0,1.02381,0.90531,1.37500,1.02381
56155,1.0,23.0,3.0,10.0,5.0,9.0,1.0,1.0,0.0,4.0,...,1.0,22046.0,20071.0,8.2,281.0,76.0,1.07317,1.35833,2.00000,1.07317
56156,1.0,20.0,5.0,17.0,7.0,20.0,1.0,1.0,0.0,1.0,...,0.0,20931.0,18496.0,8.4,267.0,63.0,1.04762,1.34759,2.42857,1.04762
56157,0.0,22.0,7.0,9.0,6.0,6.0,1.0,1.0,0.0,0.0,...,1.0,21548.0,18016.0,8.4,270.0,56.0,1.02381,1.08404,1.50000,1.02381

In [13]:
df_Average.to_excel(excel_writer = "C:/Users/linhc/OneDrive/Documents/Sproj/DataCollection/Importantfiles/TrainingValData/AverageTrainingValNewVar.xlsx")
df_Skilled.to_excel(excel_writer = "C:/Users/linhc/OneDrive/Documents/Sproj/DataCollection/Importantfiles/TrainingValData/SkilledTrainingValNewVar.xlsx")
df_Elite.to_excel(excel_writer = "C:/Users/linhc/OneDrive/Documents/Sproj/DataCollection/Importantfiles/TrainingValData/EliteTrainingValNewVar.xlsx")

In [14]:
df_Average = pd.read_excel(r'C:\Users\linhc\OneDrive\Documents\Sproj\DataCollection\Importantfiles\TrainingValData\AverageTrainingValNewVar.xlsx')
df_Skilled = pd.read_excel(r'C:\Users\linhc\OneDrive\Documents\Sproj\DataCollection\Importantfiles\TrainingValData\SkilledTrainingValNewVar.xlsx')
df_Elite = pd.read_excel(r'C:\Users\linhc\OneDrive\Documents\Sproj\DataCollection\Importantfiles\TrainingValData\EliteTrainingValNewVar.xlsx')

In [15]:
df_Elite

,Unnamed: 0,blueWins,blueWardsPlaced,blueWardsDestroyed,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,blueHeraldsBarons,...,redTowersDestroyed,redTotalGold,redTotalDamageToChampions,redAvgLevel,redTotalMinionsKilled,redTotalJungleMinionsKilled,blue/redAvgLevel,blue/redTotalDamageToChampions,red/blueKills,blueAvgLevel/redAvgLevel
0,0,0,32,5,10,15,15,0,0,0,...,1,26016,22836,8.4,279,69,1.00000,1.09940,0.66667,1.00000
1,1,1,49,6,10,14,6,1,1,0,...,1,25835,20998,8.6,301,77,0.97674,0.92795,0.71429,0.97674
2,2,1,26,2,17,10,24,2,1,1,...,1,23499,25089,8.6,268,80,1.06977,1.20710,1.70000,1.06977
3,3,1,106,8,10,8,18,2,1,1,...,0,21625,21831,8.4,297,76,1.02381,1.09880,1.25000,1.02381
4,4,1,31,10,22,7,24,3,2,1,...,0,21954,19995,8.4,293,79,1.11905,1.73458,3.14286,1.11905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8626,8631,1,24,7,6,7,8,1,1,0,...,0,23558,19954,8.6,340,100,1.00000,0.80946,0.85714,1.00000
8627,8632,1,20,8,15,9,13,1,1,0,...,1,24741,23249,8.8,317,79,1.00000,0.96520,1.66667,1.00000
8628,8633,1,26,4,17,16,21,3,2,1,...,0,25491,31258,8.6,246,62,1.00000,1.12246,1.06250,1.00000
8629,8634,1,27,9,7,13,11,1,1,0,...,1,25270,21193,9.0,297,68,0.97778,1.01321,0.53846,0.97778
8630,8635,0,20,4,8,13,4,1,0,1,...,1,28009,24678,9.6,387,87,0.91667,0.65694,0.61538,0.91667

In [16]:
#Drop 1st column
df_Elite = df_Elite.iloc[: , 1:]
df_Average = df_Average.iloc[: , 1:]
df_Skilled = df_Skilled.iloc[: , 1:]

In [17]:
df_Elite

,blueWins,blueWardsPlaced,blueWardsDestroyed,blueKills,blueDeaths,blueAssists,blueEliteMonsters,blueDragons,blueHeraldsBarons,blueTowersDestroyed,...,redTowersDestroyed,redTotalGold,redTotalDamageToChampions,redAvgLevel,redTotalMinionsKilled,redTotalJungleMinionsKilled,blue/redAvgLevel,blue/redTotalDamageToChampions,red/blueKills,blueAvgLevel/redAvgLevel
0,0,32,5,10,15,15,0,0,0,1,...,1,26016,22836,8.4,279,69,1.00000,1.09940,0.66667,1.00000
1,1,49,6,10,14,6,1,1,0,0,...,1,25835,20998,8.6,301,77,0.97674,0.92795,0.71429,0.97674
2,1,26,2,17,10,24,2,1,1,0,...,1,23499,25089,8.6,268,80,1.06977,1.20710,1.70000,1.06977
3,1,106,8,10,8,18,2,1,1,0,...,0,21625,21831,8.4,297,76,1.02381,1.09880,1.25000,1.02381
4,1,31,10,22,7,24,3,2,1,2,...,0,21954,19995,8.4,293,79,1.11905,1.73458,3.14286,1.11905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8626,1,24,7,6,7,8,1,1,0,0,...,0,23558,19954,8.6,340,100,1.00000,0.80946,0.85714,1.00000
8627,1,20,8,15,9,13,1,1,0,1,...,1,24741,23249,8.8,317,79,1.00000,0.96520,1.66667,1.00000
8628,1,26,4,17,16,21,3,2,1,1,...,0,25491,31258,8.6,246,62,1.00000,1.12246,1.06250,1.00000
8629,1,27,9,7,13,11,1,1,0,0,...,1,25270,21193,9.0,297,68,0.97778,1.01321,0.53846,0.97778
8630,0,20,4,8,13,4,1,0,1,0,...,1,28009,24678,9.6,387,87,0.91667,0.65694,0.61538,0.91667

# Cross Validation spliting data

## Getting training-valdata

In [18]:
def splitingDataFold(df):
    df = df.copy()
    #spliting data test- training
    x = df.iloc[:, 1:34]
    y = df.iloc[:, 0]
    #Scale the data
    scaler = StandardScaler()
    x = scaler.fit_transform(x)
    kf = KFold(n_splits=5, random_state = None, shuffle=True)
    #xTrain,xTest,yTrain,yTest = train_test_split(x,y,train_size=0.8,shuffle=True,random_state=42)
    #dataframe not numpy array - try differetn appoarch
    xTrain=[]
    yTrain=[]
    yTest=[]
    xTest=[]
    for train_index, test_index in kf.split(x):
        print("TRAIN:", train_index, "TEST:", test_index)
        xTrain.append(x[train_index])
        #print(x[train_index])
        xTest.append(x[test_index])
        yTrain.append(y[train_index])
        yTest.append(y[test_index])
    
    return xTrain,xTest,yTrain,yTest

In [19]:
xTrain_Elite,xTest_Elite,yTrain_Elite,yTest_Elite = splitingDataFold(df_Elite)
print ("Training set: {} samples".format(len(xTrain_Elite[0])))
print ("Test set: {} samples".format(len(xTest_Elite[0])))

TRAIN: [   0    2    3 ... 8628 8629 8630] TEST: [   1   13   14 ... 8606 8610 8614]
TRAIN: [   0    1    2 ... 8628 8629 8630] TEST: [   3   23   24 ... 8617 8624 8626]
TRAIN: [   1    2    3 ... 8628 8629 8630] TEST: [   0    5    7 ... 8620 8621 8627]
TRAIN: [   0    1    2 ... 8628 8629 8630] TEST: [  10   20   25 ... 8622 8623 8625]
TRAIN: [   0    1    3 ... 8625 8626 8627] TEST: [   2    4    6 ... 8628 8629 8630]
Training set: 6904 samples
Test set: 1727 samples

In [20]:
xTrain_Skilled,xTest_Skilled,yTrain_Skilled,yTest_Skilled = splitingDataFold(df_Skilled)
print ("Training set: {} samples".format(len(xTrain_Skilled[0])))
print ("Test set: {} samples".format(len(xTest_Skilled[0])))

TRAIN: [    1     2     3 ... 22686 22687 22688] TEST: [    0     4     5 ... 22678 22680 22681]
TRAIN: [    0     1     2 ... 22686 22687 22688] TEST: [   13    14    18 ... 22677 22679 22685]
TRAIN: [    0     1     2 ... 22685 22686 22687] TEST: [    7    10    16 ... 22660 22668 22688]
TRAIN: [    0     1     4 ... 22685 22686 22688] TEST: [    2     3    11 ... 22669 22674 22687]
TRAIN: [    0     2     3 ... 22685 22687 22688] TEST: [    1     6     8 ... 22683 22684 22686]
Training set: 18151 samples
Test set: 4538 samples

In [21]:
xTrain_Average,xTest_Average,yTrain_Average,yTest_Average = splitingDataFold(df_Average)
print ("Training set: {} samples".format(len(xTrain_Average[0])))
print ("Test set: {} samples".format(len(xTest_Average[0])))

TRAIN: [    0     2     4 ... 56112 56113 56114] TEST: [    1     3     7 ... 56105 56107 56110]
TRAIN: [    0     1     2 ... 56111 56112 56114] TEST: [   10    14    17 ... 56106 56109 56113]
TRAIN: [    0     1     2 ... 56110 56113 56114] TEST: [   11    15    21 ... 56102 56111 56112]
TRAIN: [    0     1     3 ... 56112 56113 56114] TEST: [    2     5     9 ... 56103 56104 56108]
TRAIN: [    1     2     3 ... 56111 56112 56113] TEST: [    0     4     6 ... 56094 56095 56114]
Training set: 44892 samples
Test set: 11223 samples

### Training logistic regression

In [26]:
def trainingModelLogisticRegression(x_train,y_train,reg,sol):
    lr = LogisticRegression(penalty=reg, solver=sol,max_iter=1000)
    lr.fit(x_train,y_train)
    return lr

#### l1 regulization

In [27]:
trainedEliteLrL1=[]
trainedAverageLrL1=[]
trainedSkilledLrL1=[]
for i in range(0,5):
    trainedEliteLrL1.append(trainingModelLogisticRegression(xTrain_Elite[i],yTrain_Elite[i],'l1','liblinear'))
    trainedAverageLrL1.append(trainingModelLogisticRegression(xTrain_Average[i],yTrain_Average[i],'l1','liblinear'))
    trainedSkilledLrL1.append(trainingModelLogisticRegression(xTrain_Skilled[i],yTrain_Skilled[i],'l1','liblinear'))

#### l2 regulization

In [28]:
trainedEliteLrL2=[]
trainedAverageLrL2=[]
trainedSkilledLrL2=[]
for i in range(0,5):
    trainedEliteLrL2.append(trainingModelLogisticRegression(xTrain_Elite[i],yTrain_Elite[i],'l2','saga'))
    trainedAverageLrL2.append(trainingModelLogisticRegression(xTrain_Average[i],yTrain_Average[i],'l2','saga'))
    trainedSkilledLrL2.append(trainingModelLogisticRegression(xTrain_Skilled[i],yTrain_Skilled[i],'l2','saga'))

#### No Regulaztion

In [30]:
trainedEliteLrNone=[]
trainedAverageLrNone=[]
trainedSkilledLrNone=[]
for i in range(0,5):
    trainedEliteLrNone.append(trainingModelLogisticRegression(xTrain_Elite[i],yTrain_Elite[i],'none','sag'))
    trainedAverageLrNone.append(trainingModelLogisticRegression(xTrain_Average[i],yTrain_Average[i],'none','sag'))
    trainedSkilledLrNone.append(trainingModelLogisticRegression(xTrain_Skilled[i],yTrain_Skilled[i],'none','sag'))

### Tesing Model

In [31]:
def testingLr(lr,x_test,y_test):
    name = ['','fold 1','fold 2','fold 3','fold 4','fold 5','Average']
    acc = ['Accuracy']
    pre = ['Precision']
    re = ['Recall']
    f1 = ['F1 Score']
    sumacc=0
    sumf1=0
    sumpre=0
    sumre= 0

    for i in range(0,5):
        
        testEliteLr = lr[i].predict(x_test[i])
        testEliteLr_prob = lr[i].predict_proba(x_test[i])
        
        accs= accuracy_score(y_test[i], testEliteLr)
        pres= precision_score(y_test[i], testEliteLr)
        res = recall_score(y_test[i], testEliteLr)
        f1s = f1_score(y_test[i], testEliteLr)
        
        sumacc =sumacc+accs
        sumpre =sumpre+pres
        sumre = sumre +res
        sumf1 =sumf1+f1s
        
        acc.append(' {:.5f}'.format(accs))
        pre.append(' {:.5f}'.format(pres))
        re.append(' {:.5f}'.format(res))
        f1.append(' {:.5f}'.format(f1s))
        
    acc.append(' {:.5f}'.format(sumacc/5))
    pre.append(' {:.5f}'.format(sumpre/5))
    re.append(' {:.5f}'.format(sumre/5))
    f1.append(' {:.5f}'.format(sumf1/5))
    
    table=[]
    table.append(name)
    table.append(acc)
    table.append(pre)
    table.append(re)
    table.append(f1)
    
    print(tabulate(table))

### Coefficients

In [32]:
def coefficientsLr(model):
    coefficients = np.hstack((model.intercept_,model.coef_[0]))
    name = ['blueWardsPlaced','blueWardsDestroyed','blueKills','blueDeaths','blueAssists','blueEliteMonsters','blueDragons','blueHeraldsBarons','blueTowersDestroyed','blueTotalGold','blueTotalDamageToChampions','blueAvgLevel','blueTotalMinionsKilled','blueTotalJungleMinionsKilled','blueGoldDiff','redWardsPlaced','redWardsDestroyed','redKills','redDeaths','redAssists','redEliteMonsters','redDragons','redHeraldsBarons','redTowersDestroyed','redTotalGold','redTotalDamageToChampions','redAvgLevel','redTotalMinionsKilled','redTotalJungleMinionsKilled','blue/redAvgLevel','blue/redTotalDamageToChampions','red/blueKills','blueAvgLevel/redAvgLevel']
    return name,coefficients

### Elite Data

#### Testing data

In [33]:
#No regularization
testingLr(trainedEliteLrNone,xTest_Elite,yTest_Elite)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.75738  0.78911  0.77115  0.78853  0.78621  0.77848
Precision  0.76125  0.79708  0.77871  0.79216  0.80422  0.78668
Recall     0.75688  0.76905  0.75610  0.77830  0.77252  0.76657
F1 Score   0.75906  0.78282  0.76724  0.78517  0.78805  0.77647
---------  -------  -------  -------  -------  -------  -------

In [34]:
#L1 regularization
testingLr(trainedEliteLrL1,xTest_Elite,yTest_Elite)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.75738  0.78795  0.77231  0.78621  0.78505  0.77778
Precision  0.76125  0.79444  0.77924  0.78774  0.80234  0.78500
Recall     0.75688  0.77022  0.75842  0.77946  0.77252  0.76750
F1 Score   0.75906  0.78214  0.76869  0.78358  0.78715  0.77612
---------  -------  -------  -------  -------  -------  -------

In [35]:
#L2 regularization
testingLr(trainedEliteLrL2,xTest_Elite,yTest_Elite)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.75738  0.78911  0.77115  0.78737  0.78563  0.77813
Precision  0.76125  0.79636  0.77871  0.78960  0.80328  0.78584
Recall     0.75688  0.77022  0.75610  0.77946  0.77252  0.76704
F1 Score   0.75906  0.78308  0.76724  0.78450  0.78760  0.77629
---------  -------  -------  -------  -------  -------  -------

#### Training data

In [36]:
#No regularization
testingLr(trainedEliteLrNone,xTrain_Elite,yTrain_Elite)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.78592  0.77828  0.78306  0.77886  0.77886  0.78099
Precision  0.79124  0.78490  0.78932  0.78691  0.78563  0.78760
Recall     0.77797  0.77113  0.77522  0.76857  0.76532  0.77164
F1 Score   0.78455  0.77796  0.78220  0.77763  0.77534  0.77954
---------  -------  -------  -------  -------  -------  -------

In [37]:
#L1 regularization
testingLr(trainedEliteLrL1,xTrain_Elite,yTrain_Elite)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.78607  0.77799  0.78277  0.77987  0.77871  0.78108
Precision  0.79096  0.78444  0.78903  0.78735  0.78455  0.78726
Recall     0.77884  0.77113  0.77493  0.77058  0.76677  0.77245
F1 Score   0.78485  0.77773  0.78191  0.77888  0.77556  0.77979
---------  -------  -------  -------  -------  -------  -------

In [38]:
#L2 regularization
testingLr(trainedEliteLrL2,xTrain_Elite,yTrain_Elite)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.78607  0.77799  0.78306  0.77857  0.77886  0.78091
Precision  0.79164  0.78444  0.78932  0.78611  0.78495  0.78729
Recall     0.77768  0.77113  0.77522  0.76914  0.76648  0.77193
F1 Score   0.78460  0.77773  0.78220  0.77754  0.77561  0.77953
---------  -------  -------  -------  -------  -------  -------

#### Coefficient

In [39]:
#Take fold 2 as L1 regularization has highest accuracy
#L1 regularization
name,coef = coefficientsLr(trainedEliteLrL1[1])
df = pd.DataFrame(data={'variable': ['Intercept'] + name, 'coefficient': coef})
df = df.sort_values(by='coefficient')
print(df.to_markdown())

|    | variable                       |   coefficient |
|---:|:-------------------------------|--------------:|
| 25 | redTotalGold                   |   -0.536262   |
| 22 | redDragons                     |   -0.0918454  |
| 21 | redEliteMonsters               |   -0.08218    |
| 28 | redTotalMinionsKilled          |   -0.0624741  |
| 16 | redWardsPlaced                 |   -0.0186377  |
| 29 | redTotalJungleMinionsKilled    |   -0.00883817 |
|  1 | blueWardsPlaced                |   -0.00807435 |
| 20 | redAssists                     |   -0.0051382  |
| 11 | blueTotalDamageToChampions     |    0          |
|  6 | blueEliteMonsters              |    0          |
|  8 | blueHeraldsBarons              |    0          |
| 19 | redDeaths                      |    0          |
| 27 | redAvgLevel                    |    0          |
|  4 | blueDeaths                     |    0          |
| 13 | blueTotalMinionsKilled         |    0.00775532 |
|  9 | blueTowersDestroyed            |    0.00902779 |
| 23 | redHeraldsBarons               |    0.0110005  |
| 24 | redTowersDestroyed             |    0.0136371  |
| 17 | redWardsDestroyed              |    0.0317843  |
|  3 | blueKills                      |    0.0411423  |
|  5 | blueAssists                    |    0.060426   |
| 18 | redKills                       |    0.06108    |
| 12 | blueAvgLevel                   |    0.0659464  |
|  0 | Intercept                      |    0.0716266  |
| 14 | blueTotalJungleMinionsKilled   |    0.0754128  |
| 26 | redTotalDamageToChampions      |    0.0780907  |
|  2 | blueWardsDestroyed             |    0.0784801  |
| 33 | blueAvgLevel/redAvgLevel       |    0.0912698  |
|  7 | blueDragons                    |    0.126909   |
| 31 | blue/redTotalDamageToChampions |    0.154063   |
| 32 | red/blueKills                  |    0.241259   |
| 30 | blue/redAvgLevel               |    0.256666   |
| 10 | blueTotalGold                  |    0.382573   |
| 15 | blueGoldDiff                   |    0.533042   |

### Skilled Data

#### Testing data

In [40]:
#No regularization
testingLr(trainedSkilledLrNone,xTest_Skilled,yTest_Skilled)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76509  0.75474  0.77259  0.75474  0.75931  0.76129
Precision  0.76007  0.75156  0.77753  0.75169  0.76178  0.76053
Recall     0.75801  0.75323  0.76731  0.74731  0.75166  0.75550
F1 Score   0.75904  0.75239  0.77239  0.74949  0.75668  0.75800
---------  -------  -------  -------  -------  -------  -------

In [41]:
#L1 regularization
testingLr(trainedSkilledLrL1,xTest_Skilled,yTest_Skilled)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76554  0.75496  0.77259  0.75562  0.75975  0.76169
Precision  0.76053  0.75167  0.77778  0.75214  0.76270  0.76096
Recall     0.75847  0.75367  0.76687  0.74910  0.75122  0.75587
F1 Score   0.75949  0.75267  0.77229  0.75062  0.75691  0.75840
---------  -------  -------  -------  -------  -------  -------

In [42]:
#L2 regularization
testingLr(trainedSkilledLrL2,xTest_Skilled,yTest_Skilled)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76532  0.75474  0.77237  0.75518  0.75953  0.76143
Precision  0.76018  0.75156  0.77719  0.75192  0.76235  0.76064
Recall     0.75847  0.75323  0.76731  0.74820  0.75122  0.75569
F1 Score   0.75932  0.75239  0.77222  0.75006  0.75674  0.75815
---------  -------  -------  -------  -------  -------  -------

#### Training data

In [43]:
#No regularization
testingLr(trainedSkilledLrNone,xTrain_Skilled,yTrain_Skilled)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76089  0.76271  0.75968  0.76216  0.76190  0.76147
Precision  0.76088  0.76172  0.75843  0.76261  0.75972  0.76067
Recall     0.75616  0.75757  0.75198  0.75558  0.75786  0.75583
F1 Score   0.75851  0.75964  0.75519  0.75908  0.75879  0.75824
---------  -------  -------  -------  -------  -------  -------

In [44]:
#L1 regularization
testingLr(trainedSkilledLrL1,xTrain_Skilled,yTrain_Skilled)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76078  0.76271  0.75963  0.76227  0.76162  0.76140
Precision  0.76083  0.76161  0.75817  0.76214  0.75947  0.76044
Recall     0.75594  0.75779  0.75232  0.75680  0.75753  0.75608
F1 Score   0.75838  0.75969  0.75523  0.75946  0.75850  0.75825
---------  -------  -------  -------  -------  -------  -------

In [45]:
#L2 regularization
testingLr(trainedSkilledLrL2,xTrain_Skilled,yTrain_Skilled)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76089  0.76277  0.75968  0.76227  0.76184  0.76149
Precision  0.76094  0.76175  0.75831  0.76243  0.75964  0.76061
Recall     0.75605  0.75768  0.75221  0.75625  0.75786  0.75601
F1 Score   0.75849  0.75971  0.75525  0.75933  0.75875  0.75830
---------  -------  -------  -------  -------  -------  -------

#### Coefficients

In [46]:
#Take fold 3 as L1 regularization has highest accuracy
#L1 regularization
name,coef = coefficientsLr(trainedSkilledLrL1[2])
df = pd.DataFrame(data={'variable': ['Intercept'] + name, 'coefficient': coef})
df = df.sort_values(by='coefficient')
print(df.to_markdown())

|    | variable                       |   coefficient |
|---:|:-------------------------------|--------------:|
| 25 | redTotalGold                   |  -0.18631     |
| 26 | redTotalDamageToChampions      |  -0.171919    |
| 21 | redEliteMonsters               |  -0.105374    |
| 29 | redTotalJungleMinionsKilled    |  -0.0764391   |
|  9 | blueTowersDestroyed            |  -0.0658751   |
| 22 | redDragons                     |  -0.0442754   |
| 17 | redWardsDestroyed              |  -0.0431543   |
| 31 | blue/redTotalDamageToChampions |  -0.0266414   |
|  0 | Intercept                      |  -0.0265802   |
| 28 | redTotalMinionsKilled          |  -0.0175977   |
| 16 | redWardsPlaced                 |  -0.0150701   |
| 20 | redAssists                     |  -0.0141921   |
| 27 | redAvgLevel                    |  -0.00719898  |
| 19 | redDeaths                      |   0           |
| 12 | blueAvgLevel                   |   0           |
|  4 | blueDeaths                     |   0           |
|  8 | blueHeraldsBarons              |   0           |
|  1 | blueWardsPlaced                |   7.82659e-05 |
| 24 | redTowersDestroyed             |   0.0103377   |
| 23 | redHeraldsBarons               |   0.0280593   |
|  5 | blueAssists                    |   0.0372188   |
|  2 | blueWardsDestroyed             |   0.0376113   |
| 18 | redKills                       |   0.0391319   |
| 14 | blueTotalJungleMinionsKilled   |   0.0540625   |
| 13 | blueTotalMinionsKilled         |   0.0657244   |
|  3 | blueKills                      |   0.0675992   |
|  6 | blueEliteMonsters              |   0.0761819   |
| 10 | blueTotalGold                  |   0.0962501   |
| 32 | red/blueKills                  |   0.102317    |
| 11 | blueTotalDamageToChampions     |   0.113977    |
|  7 | blueDragons                    |   0.122448    |
| 33 | blueAvgLevel/redAvgLevel       |   0.138815    |
| 30 | blue/redAvgLevel               |   0.146745    |
| 15 | blueGoldDiff                   |   0.919006    |

### Average Data

#### Testing data

In [47]:
#No regularization
testingLr(trainedAverageLrNone,xTest_Average,yTest_Average)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.75764  0.76619  0.76022  0.75880  0.76548  0.76167
Precision  0.75968  0.77297  0.76110  0.75745  0.77047  0.76433
Recall     0.75427  0.76292  0.75961  0.75704  0.76939  0.76065
F1 Score   0.75697  0.76791  0.76035  0.75724  0.76993  0.76248
---------  -------  -------  -------  -------  -------  -------

In [48]:
#L1 regularization
testingLr(trainedAverageLrL1,xTest_Average,yTest_Average)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.75764  0.76709  0.76031  0.75862  0.76548  0.76183
Precision  0.75987  0.77415  0.76133  0.75736  0.77085  0.76471
Recall     0.75392  0.76327  0.75943  0.75668  0.76869  0.76040
F1 Score   0.75688  0.76867  0.76038  0.75702  0.76977  0.76254
---------  -------  -------  -------  -------  -------  -------

In [49]:
#L2 regularization
testingLr(trainedAverageLrL2,xTest_Average,yTest_Average)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.75755  0.76646  0.76040  0.75871  0.76539  0.76170
Precision  0.75964  0.77338  0.76137  0.75740  0.77043  0.76444
Recall     0.75410  0.76292  0.75961  0.75686  0.76922  0.76054
F1 Score   0.75686  0.76811  0.76049  0.75713  0.76982  0.76248
---------  -------  -------  -------  -------  -------  -------

#### Training data

In [50]:
#No regularization
testingLr(trainedAverageLrNone,xTrain_Average,yTrain_Average)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76328  0.76169  0.76279  0.76357  0.76178  0.76262
Precision  0.76655  0.76378  0.76602  0.76640  0.76422  0.76539
Recall     0.76211  0.76053  0.76158  0.76437  0.75892  0.76150
F1 Score   0.76432  0.76215  0.76379  0.76538  0.76156  0.76344
---------  -------  -------  -------  -------  -------  -------

In [51]:
#L1 regularization
testingLr(trainedAverageLrL1,xTrain_Average,yTrain_Average)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76314  0.76167  0.76301  0.76372  0.76183  0.76267
Precision  0.76668  0.76412  0.76660  0.76664  0.76474  0.76575
Recall     0.76149  0.75982  0.76114  0.76437  0.75808  0.76098
F1 Score   0.76407  0.76196  0.76386  0.76550  0.76139  0.76336
---------  -------  -------  -------  -------  -------  -------

In [52]:
#L2 regularization
testingLr(trainedAverageLrL2,xTrain_Average,yTrain_Average)

---------  -------  -------  -------  -------  -------  -------
           fold 1   fold 2   fold 3   fold 4   fold 5   Average
Accuracy   0.76339  0.76172  0.76290  0.76359  0.76183  0.76268
Precision  0.76669  0.76384  0.76619  0.76648  0.76438  0.76552
Recall     0.76215  0.76048  0.76158  0.76428  0.75874  0.76145
F1 Score   0.76442  0.76216  0.76388  0.76538  0.76155  0.76348
---------  -------  -------  -------  -------  -------  -------

#### Coefficients

In [53]:
#Take fold 2 as L1 regularization has highest accuracy
#L1 regularization
name,coef = coefficientsLr(trainedAverageLrL1[1])
df = pd.DataFrame(data={'variable': ['Intercept'] + name, 'coefficient': coef})
df = df.sort_values(by='coefficient')
print(df.to_markdown())

|    | variable                       |   coefficient |
|---:|:-------------------------------|--------------:|
| 25 | redTotalGold                   |  -0.422075    |
| 22 | redDragons                     |  -0.181083    |
| 27 | redAvgLevel                    |  -0.100534    |
| 28 | redTotalMinionsKilled          |  -0.0997842   |
|  9 | blueTowersDestroyed            |  -0.0649531   |
| 18 | redKills                       |  -0.0644871   |
|  5 | blueAssists                    |  -0.063473    |
| 23 | redHeraldsBarons               |  -0.0468237   |
| 29 | redTotalJungleMinionsKilled    |  -0.0425004   |
| 11 | blueTotalDamageToChampions     |  -0.024367    |
|  4 | blueDeaths                     |  -0.0113622   |
| 16 | redWardsPlaced                 |  -0.0113454   |
| 33 | blueAvgLevel/redAvgLevel       |  -0.00760646  |
|  1 | blueWardsPlaced                |  -0.00102879  |
| 21 | redEliteMonsters               |  -0.000489539 |
| 30 | blue/redAvgLevel               |   0           |
| 17 | redWardsDestroyed              |   0           |
|  3 | blueKills                      |   0           |
|  8 | blueHeraldsBarons              |   0           |
|  2 | blueWardsDestroyed             |   0.00516814  |
| 19 | redDeaths                      |   0.0162718   |
|  6 | blueEliteMonsters              |   0.0163124   |
| 14 | blueTotalJungleMinionsKilled   |   0.0327936   |
| 26 | redTotalDamageToChampions      |   0.0343812   |
|  0 | Intercept                      |   0.0371787   |
| 13 | blueTotalMinionsKilled         |   0.0567345   |
| 24 | redTowersDestroyed             |   0.0574101   |
| 20 | redAssists                     |   0.0596648   |
| 32 | red/blueKills                  |   0.0827021   |
| 12 | blueAvgLevel                   |   0.110035    |
|  7 | blueDragons                    |   0.19918     |
| 31 | blue/redTotalDamageToChampions |   0.201542    |
| 10 | blueTotalGold                  |   0.47243     |
| 15 | blueGoldDiff                   |   0.608526    |

In [ ]:
from sklearn.ensemble import RandomForestClassifier